controller_list:
  - name: fake_arm_group_controller
    type: $(arg execution_type)
    joints:
      - Joint_0
      - Joint_1
      - Joint_2
      - Joint_3
      - Joint_4
      - Joint_5
initial:  # Define initial robot poses.
  - group: arm_group
    pose: home