controller_list:
  - name: fake_dorna_2_arm_controller
    type: $(arg execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
  - name: fake_end_effector_controller
    type: $(arg execution_type)
    joints:
      - joint5
initial:  # Define initial robot poses.
  - group: dorna_2_arm
    pose: all_0